[![Open In Colab](https://colab.research.google.com/assets/colab-badge.svg)](https://colab.research.google.com/github/conveneml/supervised/blob/main/myintro.ipynb)

## Stuff to do before starting

Sign up to github at github.com
Sign up to kaggle at kaggle.com

In [6]:
# Load libraries
import pandas as pd
from matplotlib import pyplot

#Load CSV files with Pandas
from pandas import read_csv
filename = '~/Downloads/diabetes.csv'
dataset = read_csv(filename)


#Load file from URL
from pandas import read_csv
url = 'https://bit.ly/33EM5Kh'
names = ['age', 'class']
dataset = read_csv(url, names=names)


#Load file using pandas_datareader from the Yahoo Finance and FRED websites
import pandas_datareader.data as web
stk_tickers = ['MSFT', 'IBM', 'GOOGL']
ccy_tickers = ['DEXJPUS', 'DEXUSUK']
idx_tickers = ['SP500', 'DJIA', 'VIXCLS']
stk_data = web.DataReader(stk_tickers, 'yahoo')
ccy_data = web.DataReader(ccy_tickers, 'fred')
idx_data = web.DataReader(idx_tickers, 'fred')

In [7]:
stk_data

Attributes   Adj Close                                Close              \
Symbols           MSFT         IBM        GOOGL        MSFT         IBM
Date
2017-01-19   57.925182  126.790779   824.369995   62.299999  159.474182
2017-01-20   58.334286  129.633575   828.169983   62.740002  163.049713
2017-01-23   58.538834  129.998398   844.429993   62.959999  163.508606
2017-01-24   59.059513  133.699997   849.530029   63.520000  168.164429
2017-01-25   59.208275  135.516632   858.450012   63.680000  170.449326
...                ...         ...          ...         ...         ...
2022-01-10  314.269989  135.029999  2773.389893  314.269989  135.029999
2022-01-11  314.980011  132.869995  2794.719971  314.980011  132.869995
2022-01-12  318.269989  133.589996  2828.610107  318.269989  133.589996
2022-01-13  304.799988  134.759995  2771.739990  304.799988  134.759995
2022-01-14  310.200012  134.210007  2789.610107  310.200012  134.210007

Attributes                     High                                  Low  \
Symbols           GOOGL        MSFT         IBM        GOOGL        MSFT
Date
2017-01-19   824.369995   62.980000  160.086044   833.000000   62.200001
2017-01-20   828.169983   62.820000  163.135757   829.239990   62.369999
2017-01-23   844.429993   63.119999  163.718933   845.539978   62.570000
2017-01-24   849.530029   63.740002  168.260040   851.520020   62.939999
2017-01-25   858.450012   64.099998  171.367111   858.789978   63.450001
...                 ...         ...         ...          ...         ...
2022-01-10  2773.389893  314.720001  136.199997  2776.389893  304.690002
2022-01-11  2794.719971  316.609985  133.250000  2804.320068  309.890015
2022-01-12  2828.610107  323.410004  134.470001  2852.159912  317.079987
2022-01-13  2771.739990  320.880005  136.050003  2857.000000  304.000000
2022-01-14  2789.610107  310.820007  135.139999  2814.840088  303.750000

Attributes                                 Open                           \
Symbols            IBM        GOOGL        MSFT         IBM        GOOGL
Date
2017-01-19  158.508606   823.960022   62.240002  159.617584   829.000000
2017-01-20  158.699814   824.599976   62.669998  160.430206   829.090027
2017-01-23  162.533463   828.700012   62.700001  162.600388   831.609985
2017-01-24  163.632889   842.280029   63.200001  163.824097   846.979980
2017-01-25  168.384323   849.739990   63.950001  168.508606   853.549988
...                ...          ...         ...         ...          ...
2022-01-10  133.380005  2663.290039  309.489990  134.470001  2701.560059
2022-01-11  127.970001  2733.850098  313.380005  130.520004  2760.139893
2022-01-12  131.369995  2813.889893  319.670013  133.250000  2823.000000
2022-01-13  133.559998  2768.179932  320.470001  133.899994  2830.800049
2022-01-14  133.300003  2739.969971  304.250000  134.550003  2741.580078

Attributes      Volume
Symbols           MSFT         IBM      GOOGL
Date
2017-01-19  18451700.0   7283716.0  1070500.0
2017-01-20  30213500.0  13273740.0  1306200.0
2017-01-23  23097600.0   5730197.0  2457400.0
2017-01-24  24672900.0   7272210.0  1688400.0
2017-01-25  23672700.0   6194935.0  1655400.0
...                ...         ...        ...
2022-01-10  44289500.0   5432800.0  2220400.0
2022-01-11  29386800.0  11105300.0  1436500.0
2022-01-12  34372200.0   5352000.0  1305400.0
2022-01-13  45366000.0   4868300.0  1571800.0
2022-01-14  39823500.0   5309200.0  1482100.0

[1258 rows x 18 columns]